name: Build TodoList App

on:
  push:
    branches: [ master ]

jobs:
  build-angular:
    runs-on: ubantu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
           node-version: 14.x
           
      - name: Install dependecies
        run: npm install

      - name: build
        run: npm run build

      
