name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger this workflow only on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Adjust if using a different Node version

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build -- --output-path=docs --base-href /todolist_app/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs  # This is the output folder of your Angular build